<!-- https://www.html-code-generator.com/html/drop-down/country-names -->
<option value="AX">Iles Aland</option>
<option value="AL">Albanie</option>
<option value="AD">Andorre</option>
<option value="AT">Autriche</option>
<option value="BY">Biélorussie</option>
<option value="BE">Belgique</option>
<option value="BA">Bosnie Herzégovine</option>
<option value="BG">Bulgarie</option>
<option value="HR">Croatie</option>
<option value="CZ">République Tchèque</option>
<option value="DK">Danemark</option>
<option value="EE">Estonie</option>
<option value="FO">Îles Féroé</option>
<option value="FI">Finlande</option>
<option value="FR">France</option>
<option value="DE">Allemagne</option>
<option value="GI">Gibraltar</option>
<option value="GR">Grèce</option>
<option value="GG">Guernesey</option>
<option value="VA">Saint-Siège (État de la Cité du Vatican)</option>
<option value="HU">Hongrie</option>
<option value="IS">Islande</option>
<option value="IE">Irlande</option>
<option value="IM">île de Man</option>
<option value="IT">Italie</option>
<option value="JE">Jersey</option>
<option value="XK">Kosovo</option>
<option value="LV">Lettonie</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Lituanie</option>
<option value="LU">Luxembourg</option>
<option value="MK">Macédoine, ancienne République yougoslave de</option>
<option value="MT">Malte</option>
<option value="MD">Moldova, République de</option>
<option value="MC">Monaco</option>
<option value="ME">Monténégro</option>
<option value="NL">Pays-Bas</option>
<option value="NO">Norvège</option>
<option value="PL">Pologne</option>
<option value="PT">Le Portugal</option>
<option value="RO">Roumanie</option>
<option value="SM">Saint Marin</option>
<option value="RS">Serbie</option>
<option value="CS">Serbie et Monténégro</option>
<option value="SK">Slovaquie</option>
<option value="SI">Slovénie</option>
<option value="ES">Espagne</option>
<option value="SJ">Svalbard et Jan Mayen</option>
<option value="SE">Suède</option>
<option selected="selected" value="CH">Suisse</option>
<option value="UA">Ukraine</option>
<option value="GB">Royaume-Uni</option>
