<!-- https://www.html-code-generator.com/html/drop-down/country-names -->
<option value="AX">Aland Islands</option>
<option value="AL">Albanien</option>
<option value="AD">Andorra</option>
<option value="AT">Österreich</option>
<option value="BY">Weissrussland</option>
<option value="BE">Belgien</option>
<option value="BA">Bosnien und Herzegowina</option>
<option value="BG">Bulgarien</option>
<option value="HR">Kroatien</option>
<option value="CZ">Tschechien</option>
<option value="DK">Dänemark</option>
<option value="EE">Estland</option>
<option value="FO">Färöer Inseln</option>
<option value="FI">Finnland</option>
<option value="FR">Frankreich</option>
<option value="DE">Deutschland</option>
<option value="GI">Gibraltar</option>
<option value="GR">Griechenland</option>
<option value="GG">Guernsey</option>
<option value="VA">Heiliger Stuhl (Staat der Vatikanstadt)</option>
<option value="HU">Ungarn</option>
<option value="IS">Island</option>
<option value="IE">Irland</option>
<option value="IM">Isle of Man</option>
<option value="IT">Italien</option>
<option value="JE">Jersey</option>
<option value="XK">Kosovo</option>
<option value="LV">Lettland</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Litauen</option>
<option value="LU">Luxemburg</option>
<option value="MK">Mazedonien, die ehemalige jugoslawische Republik</option>
<option value="MT">Malta</option>
<option value="MD">Moldawien, Republik</option>
<option value="MC">Monaco</option>
<option value="ME">Montenegro</option>
<option value="NL">Niederlande</option>
<option value="NO">Norwegen</option>
<option value="PL">Polen</option>
<option value="PT">Portugal</option>
<option value="RO">Rumänien</option>
<option value="SM">San Marino</option>
<option value="RS">Serbien</option>
<option value="CS">Serbien und Montenegro</option>
<option value="SK">Slowakei</option>
<option value="SI">Slowenien</option>
<option value="ES">Spanien</option>
<option value="SJ">Spitzbergen und Jan Mayen</option>
<option value="SE">Schweden</option>
<option selected="selected" value="CH">Schweiz</option>
<option value="UA">Ukraine</option>
<option value="GB">Vereinigtes Königreich</option>