<option value="AX">Isole Aland</option>
<option value="AL">Albania</option>
<option value="AD">Andorra</option>
<option value="AT">Austria</option>
<option value="BY">Bielorussia</option>
<option value="BE">Belgio</option>
<option value="BA">Bosnia Erzegovina</option>
<option value="BG">Bulgaria</option>
<option value="HR">Croazia</option>
<option value="CZ">Repubblica Ceca</option>
<option value="DK">Danimarca</option>
<option value="EE">Estonia</option>
<option value="FO">Isole Faroe</option>
<option value="FI">Finlandia</option>
<option value="FR">Francia</option>
<option value="DE">Germania</option>
<option value="GI">Gibilterra</option>
<option value="GR">Grecia</option>
<option value="GG">Guernsey</option>
<option value="VA">Santa Sede (Stato della Città del Vaticano)</option>
<option value="HU">Ungheria</option>
<option value="IS">Islanda</option>
<option value="IE">Irlanda</option>
<option value="IM">Isola di Man</option>
<option value="IT">Italia</option>
<option value="JE">Jersey</option>
<option value="XK">Kosovo</option>
<option value="LV">Lettonia</option>
<option value="LI">Liechtenstein</option>
<option value="LT">Lituania</option>
<option value="LU">Lussemburgo</option>
<option value="MK">Macedonia, ex Repubblica iugoslava di</option>
<option value="MT">Malta</option>
<option value="MD">Moldova, Repubblica di</option>
<option value="MC">Monaco</option>
<option value="ME">Montenegro</option>
<option value="NL">Olanda</option>
<option value="NO">Norvegia</option>
<option value="PL">Polonia</option>
<option value="PT">Portogallo</option>
<option value="RO">Romania</option>
<option value="SM">San Marino</option>
<option value="RS">Serbia</option>
<option value="CS">Serbia e Montenegro</option>
<option value="SK">Slovacchia</option>
<option value="SI">Slovenia</option>
<option value="ES">Spagna</option>
<option value="SJ">Svalbard e Jan Mayen</option>
<option value="SE">Svezia</option>
<option selected="selected" value="CH">Svizzera</option>
<option value="UA">Ucraina</option>
<option value="GB">Regno Unito</option>
